// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfP3Cp1YgzZfxCWXTRCCeeitaDNYhtvY',
    appId: '1:729218541208:web:71ded421795e1f421dd2ed',
    messagingSenderId: '729218541208',
    projectId: 'flutter-task-manager-f9246',
    authDomain: 'flutter-task-manager-f9246.firebaseapp.com',
    storageBucket: 'flutter-task-manager-f9246.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapoatvnreMXZNHS-hM4rg6BPCb3uG8rc',
    appId: '1:729218541208:android:adf1a2ebfb1fc2761dd2ed',
    messagingSenderId: '729218541208',
    projectId: 'flutter-task-manager-f9246',
    storageBucket: 'flutter-task-manager-f9246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpv-pNLRU4SROQ9D2A3r2HmfAVtuIiwA',
    appId: '1:729218541208:ios:b52b14abaa81b0931dd2ed',
    messagingSenderId: '729218541208',
    projectId: 'flutter-task-manager-f9246',
    storageBucket: 'flutter-task-manager-f9246.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpv-pNLRU4SROQ9D2A3r2HmfAVtuIiwA',
    appId: '1:729218541208:ios:b52b14abaa81b0931dd2ed',
    messagingSenderId: '729218541208',
    projectId: 'flutter-task-manager-f9246',
    storageBucket: 'flutter-task-manager-f9246.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcfP3Cp1YgzZfxCWXTRCCeeitaDNYhtvY',
    appId: '1:729218541208:web:e178e0f96e5c95ef1dd2ed',
    messagingSenderId: '729218541208',
    projectId: 'flutter-task-manager-f9246',
    authDomain: 'flutter-task-manager-f9246.firebaseapp.com',
    storageBucket: 'flutter-task-manager-f9246.firebasestorage.app',
  );

}